version: '3.8'

services:
  king-6:
    image: david-6
    build: .
    networks:
      - king-david
    ports:
      - '6000:3009'
    environment:
      -  MONGO_URI:'mongodb://mongo:27017/EmployeeDatabase'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
